### ISSUE TITLE
11.27모임 중 질문정리

### ISSUE THREAD

**Issue by Kyoo32** [Mamamoo-iOS/study#10]
1.rename

2.delegate xib?

3.pod 적용

**Comment by Yunseo** [comment]
수요일 데모때 보여줄 기술 시연 범위
- 메인화면에서 서버로 데이터 전송(텍스트, 이미지 포함)
- 메인화면에서 상세 화면으로 전환 & 상세 화면의 내용 메인리스트에서 보여줌
- 개인 정보 화면 보여주기 (기존의 사이드 ->  뷰 추가 하는 것으로 바꿈)
- 새 글 쓰기 화면에서 (이미지 넣기) , 쓴글이 서버로 전송

--월요일에 오전 질문하고 합치기, 모자르면  마무리 작업을 한다.

**Comment by luvgaram** [comment]
1.rename:  h파일 내부에서 rename하면 됨
